Repository Ocelot1210/X4_ComplexCalculator, pull requests merged in 2020-09, with the labels that each got.

#42 Add application auto update feature
  .github/workflows/build.yml
  .github/workflows/release.yml
  X4_ComplexCalculator/AssemblyInfo.cs
  X4_ComplexCalculator/Infrastructure/ApplicationUpdater.cs
  X4_ComplexCalculator/Infrastructure/ZipPackageExtractorEx.cs
  X4_ComplexCalculator/Localization/Lang.csv
  X4_ComplexCalculator/Localization/Lang.en-US.csv
  X4_ComplexCalculator/Localization/Lang.ja-JP.csv
  X4_ComplexCalculator/Main/MainWindow.xaml
  X4_ComplexCalculator/Main/MainWindowViewModel.cs
  X4_ComplexCalculator/Main/UpdateDownloadProgressDialog.xaml
  X4_ComplexCalculator/Main/UpdateDownloadProgressDialog.xaml.cs
  X4_ComplexCalculator/Main/UpdateDownloadProgressViewModel.cs
  X4_ComplexCalculator/X4_ComplexCalculator.csproj
Labels: enhancement

#45 Fix update notification is showing even if using the latest version
  X4_ComplexCalculator/Infrastructure/ApplicationUpdater.cs
Labels: bug

#47 Fix the plan not to be closed if the plan save is canceled.
  X4_ComplexCalculator/Main/WorkAreaManager.cs
Labels: bug

#48 Empire overview
  X4_ComplexCalculator/Localization/Lang.csv
  X4_ComplexCalculator/Localization/Lang.en-US.csv
  X4_ComplexCalculator/Localization/Lang.ja-JP.csv
  X4_ComplexCalculator/Main/MainWindow.xaml
  X4_ComplexCalculator/Main/MainWindowViewModel.cs
  X4_ComplexCalculator/Main/Menu/File/Export/IExport.cs
  X4_ComplexCalculator/Main/Menu/File/Import/IImport.cs
  X4_ComplexCalculator/Main/Menu/File/Import/LoadoutImport/SelectLoadoutDialog.xaml.cs
  X4_ComplexCalculator/Main/Menu/View/EmpireOverview/EmpireOverViewProductsGridItem.cs
  X4_ComplexCalculator/Main/Menu/View/EmpireOverview/EmpireOverviewWindow.xaml
  X4_ComplexCalculator/Main/Menu/View/EmpireOverview/EmpireOverviewWindow.xaml.cs
  X4_ComplexCalculator/Main/Menu/View/EmpireOverview/EmpireOverviewWindowModel.cs
  X4_ComplexCalculator/Main/Menu/View/EmpireOverview/EmpireOverviewWindowViewModel.cs
  X4_ComplexCalculator/Main/WorkArea/IWorkArea.cs
  X4_ComplexCalculator/Main/WorkArea/UI/BuildResourcesGrid/BuildResourcesGridModel.cs
  X4_ComplexCalculator/Main/WorkArea/UI/BuildResourcesGrid/BuildResourcesGridViewModel.cs
  X4_ComplexCalculator/Main/WorkArea/UI/Menu/Tab/VisiblityMenuItem.cs
  X4_ComplexCalculator/Main/WorkArea/UI/ModulesGrid/ModulesGridViewModel.cs
  X4_ComplexCalculator/Main/WorkArea/UI/ModulesGrid/SelectModule/SelectModuleWindow.xaml
  X4_ComplexCalculator/Main/WorkArea/UI/ProductsGrid/ProductsGrid.xaml
  X4_ComplexCalculator/Main/WorkArea/UI/ProductsGrid/ProductsGridModel.cs
  X4_ComplexCalculator/Main/WorkArea/UI/ProductsGrid/ProductsGridViewModel.cs
  X4_ComplexCalculator/Main/WorkArea/UI/StationSummary/StationSummaryViewModel.cs
  X4_ComplexCalculator/Main/WorkArea/UI/StationSummary/WorkForce/ModuleInfo/WorkForceModuleInfoDetailsItem.cs
  X4_ComplexCalculator/Main/WorkArea/UI/StorageAssign/StorageAssignViewModel.cs
  X4_ComplexCalculator/Main/WorkArea/UI/StoragesGrid/StoragesGridViewModel.cs
  X4_ComplexCalculator/Main/WorkArea/WorkArea.xaml
  X4_ComplexCalculator/Main/WorkArea/WorkAreaViewModel.cs
  X4_ComplexCalculator/Themes/DataGridThemes.xaml
Labels: bug, enhancement

#51 Fix not being able to export the information of some modules correctly
  X4_DataExporterWPF/Export/Module/ModuleOwnerExporter.cs
  X4_DataExporterWPF/Export/Module/ModuleProductExporter.cs
  X4_DataExporterWPF/Export/Module/ModuleResourceExporter.cs
  X4_DataExporterWPF/Export/Module/ModuleShieldExporter.cs
  X4_DataExporterWPF/Export/Module/ModuleStorageExporter.cs
  X4_DataExporterWPF/Export/Module/ModuleTurretExporter.cs
Labels: bug

#56 Fix export process of "Matrix Solar Panel".
  X4_DataExporterWPF/Export/Module/ModuleProductExporter.cs
Labels: bug

#59 建造方式を切り替えるとステーションの建造コストが膨れ上がるのを修正
  X4_ComplexCalculator/Main/WorkArea/UI/BuildResourcesGrid/BuildResourcesGridItem.cs
Labels: bug

#62 モジュールの装備を削除した際の建造リソースの計算誤りを修正
  X4_ComplexCalculator/Main/WorkArea/UI/BuildResourcesGrid/BuildResourcesGridModel.cs
Labels: bug
